[tool.poetry]
name = "fast-ui"
version = "0.1.0"
description = ""
authors = ["JFP"]
readme = "README.md"
package-mode=false

[tool.poetry.dependencies]
python = "^3.12"
fastapi = "^0.111.0"
polars = "^0.20.31"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
